### ISSUE TITLE
No module named termcolor. How can I solve this issue?

### ISSUE THREAD

**Issue by 20chix** [ThoughtfulDev/EagleEye#4]
![screen shot 2018-03-03 at 00 44 28](https://user-images.githubusercontent.com/15612171/36928131-f2c301d4-1e7a-11e8-8bbe-b666beabb362.png)

**Comment by ThoughtfulDev** [comment]
From the Folder where the eagleeye is located:
```
$ sudo apt install cmake
$ sudo pip3 install -r requirements.txt
```

**Comment by 20chix** [comment]
I think is something related to geckodriver, I downloaded it, but not sure how to install it?
![screen shot 2018-03-03 at 18 43 56](https://user-images.githubusercontent.com/15612171/36937885-cc5ae0ec-1f11-11e8-8570-419f1876d555.png)

**Comment by ThoughtfulDev** [comment]
There is not need to start the geckodriver.
Just download it and make it executable. There is no need to "install" the geckodriver
Then edit the config.json to point to the path of your geckodriver and start eagle-eye.

**Comment by 20chix** [comment]
where can I find config.json file in linux?

**Comment by ThoughtfulDev** [comment]
The config.json is in the repository...as i said have a look at [How to use](https://github.com/ThoughtfulDev/EagleEye/blob/master/README.md)

**Comment by 20chix** [comment]
Still getting the same error
![screen shot 2018-03-03 at 19 54 35](https://user-images.githubusercontent.com/15612171/36938590-a6b1ba32-1f1b-11e8-84f1-612c34ef87d9.png)

**Comment by ThoughtfulDev** [comment]
Thats because the `sudo pip3 install -r requirements.txt` failed. Did you have cmake installed?
Please post the whole pip error log.

**Comment by 20chix** [comment]
I installed Cmake,trying to upgrade python to 9.0.1

**Comment by ThoughtfulDev** [comment]
I saw some of the log in the last screen at the top.
Just do a `sudo pip3 install -r requirements.txt` from inside the eagle-eye directory and wait. if some errors popup paste the terminal output in here in a code tag.

**Comment by 20chix** [comment]
`Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0e76gh6l/cffi-1.11.5/setup.py", line 240, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0e76gh6l/cffi-1.11.5/setup.py", line 240, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-itu18mrq/cairocffi/setup.py", line 44, in <module>
        extras_require={'xcb': ['xcffib>=0.3.2']},
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-itu18mrq/cairocffi/
`

**Comment by ThoughtfulDev** [comment]
This should solve it
```
sudo apt install libffi-dev
```

After that the pip install should work.

**Comment by ThoughtfulDev** [comment]
So here is the full Update Installation instructions which should work:
```
$ git clone https://github.com/ThoughtfulDev/EagleEye
$ sudo apt install cmake libffi-dev
$ cd EagleEye && pip3 install -r requirements.txt
$ pip3 install --upgrade beautifulsoup4 html5lib
$ pip3 install spry 
```

Please report back :)

**Comment by 20chix** [comment]
```
`ros@ros-VirtualBox:~/Downloads/EagleEye$ sudo pip3 install -r requirements.txt
[sudo] password for ros: 
The directory '/home/ros/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ros/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1))
Collecting termcolor (from -r requirements.txt (line 2))
Collecting opencv-python (from -r requirements.txt (line 3))
  Downloading opencv_python-3.4.0.12-cp35-cp35m-manylinux1_x86_64.whl (24.9MB)
    100% |████████████████████████████████| 24.9MB 55kB/s 
Collecting selenium (from -r requirements.txt (line 4))
  Downloading selenium-3.9.0-py2.py3-none-any.whl (942kB)
    100% |████████████████████████████████| 952kB 636kB/s 
Collecting face_recognition (from -r requirements.txt (line 5))
  Downloading face_recognition-1.2.1-py2.py3-none-any.whl
Collecting WeasyPrint (from -r requirements.txt (line 6))
  Downloading WeasyPrint-0.42.2-py3-none-any.whl (296kB)
    100% |████████████████████████████████| 296kB 1.3MB/s 
Collecting instalooter (from -r requirements.txt (line 7))
  Downloading instaLooter-0.14.0-py2.py3-none-any.whl
Collecting numpy>=1.11.1 (from opencv-python->-r requirements.txt (line 3))
  Downloading numpy-1.14.1-cp35-cp35m-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 108kB/s 
Collecting scipy>=0.17.0 (from face_recognition->-r requirements.txt (line 5))
  Downloading scipy-1.0.0-cp35-cp35m-manylinux1_x86_64.whl (49.6MB)
    100% |████████████████████████████████| 49.6MB 27kB/s 
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition->-r requirements.txt (line 5))
Collecting dlib>=19.7 (from face_recognition->-r requirements.txt (line 5))
  Downloading dlib-19.9.0.tar.gz (3.1MB)
    100% |████████████████████████████████| 3.1MB 318kB/s 
Collecting Click>=6.0 (from face_recognition->-r requirements.txt (line 5))
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.7MB/s 
Collecting face-recognition-models>=0.3.0 (from face_recognition->-r requirements.txt (line 5))
  Downloading face_recognition_models-0.3.0.tar.gz (100.1MB)
    100% |████████████████████████████████| 100.2MB 13kB/s 
Collecting CairoSVG>=1.0.20; python_version >= "3.0" (from WeasyPrint->-r requirements.txt (line 6))
  Downloading CairoSVG-2.1.3-py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 2.2MB/s 
Collecting cffi>=0.6 (from WeasyPrint->-r requirements.txt (line 6))
  Downloading cffi-1.11.5-cp35-cp35m-manylinux1_x86_64.whl (420kB)
    100% |████████████████████████████████| 430kB 978kB/s 
Collecting cssselect2>=0.1 (from WeasyPrint->-r requirements.txt (line 6))
  Downloading cssselect2-0.2.1-py2.py3-none-any.whl
Collecting tinycss2>=0.5 (from WeasyPrint->-r requirements.txt (line 6))
  Downloading tinycss2-0.6.1-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 2.1MB/s 
Collecting Pyphen>=0.8 (from WeasyPrint->-r requirements.txt (line 6))
  Downloading Pyphen-0.9.4-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 2.0MB 390kB/s 
Collecting cairocffi>=0.5 (from WeasyPrint->-r requirements.txt (line 6))
Collecting pdfrw>=0.4 (from WeasyPrint->-r requirements.txt (line 6))
  Downloading pdfrw-0.4-py2.py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 1.5MB/s 
Collecting html5lib>=0.999999999 (from WeasyPrint->-r requirements.txt (line 6))
  Downloading html5lib-1.0.1-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 1.5MB/s 
Collecting requests~=2.18 (from instalooter->-r requirements.txt (line 7))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 2.0MB/s 
Collecting python-dateutil~=2.1 (from instalooter->-r requirements.txt (line 7))
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 1.5MB/s 
Collecting progressbar2~=3.1 (from instalooter->-r requirements.txt (line 7))
  Downloading progressbar2-3.35.2-py2.py3-none-any.whl
Requirement already satisfied: six~=1.4 in /usr/lib/python3/dist-packages (from instalooter->-r requirements.txt (line 7))
Collecting hues<1,>=0.2.2 (from instalooter->-r requirements.txt (line 7))
  Downloading hues-0.2.2-py3-none-any.whl
Requirement already satisfied: beautifulsoup4~=4.4 in /usr/lib/python3/dist-packages (from instalooter->-r requirements.txt (line 7))
Collecting docopt~=0.4 (from instalooter->-r requirements.txt (line 7))
Collecting defusedxml (from CairoSVG>=1.0.20; python_version >= "3.0"->WeasyPrint->-r requirements.txt (line 6))
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=0.6->WeasyPrint->-r requirements.txt (line 6))
Collecting webencodings>=0.4 (from tinycss2>=0.5->WeasyPrint->-r requirements.txt (line 6))
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests~=2.18->instalooter->-r requirements.txt (line 7))
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 1.8MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests~=2.18->instalooter->-r requirements.txt (line 7))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 812kB/s 
Collecting idna<2.7,>=2.5 (from requests~=2.18->instalooter->-r requirements.txt (line 7))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.9MB/s 
Collecting python-utils>=2.3.0 (from progressbar2~=3.1->instalooter->-r requirements.txt (line 7))
  Downloading python_utils-2.3.0-py2.py3-none-any.whl
Collecting PyYAML (from hues<1,>=0.2.2->instalooter->-r requirements.txt (line 7))
Installing collected packages: termcolor, numpy, opencv-python, selenium, scipy, dlib, Click, face-recognition-models, face-recognition, webencodings, tinycss2, cssselect2, defusedxml, pycparser, cffi, cairocffi, CairoSVG, Pyphen, pdfrw, html5lib, WeasyPrint, certifi, chardet, idna, requests, python-dateutil, python-utils, progressbar2, PyYAML, hues, docopt, instalooter
  Running setup.py install for dlib ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-61bjkblz/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-q0ealcj_-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Invoking CMake setup: 'cmake /tmp/pip-build-61bjkblz/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-61bjkblz/dlib/build/lib.linux-x86_64-3.5 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python3 (found version "3.5.2")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.3.dev0
    -- Enabling SSE4 instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
    -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
    -- Looking for gethostbyname
    -- Looking for gethostbyname - found
    -- Looking for connect
    -- Looking for connect - found
    -- Looking for remove
    -- Looking for remove - found
    -- Looking for shmat
    -- Looking for shmat - found
    -- Looking for IceConnectionNumber in ICE
    -- Looking for IceConnectionNumber in ICE - found
    -- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
    -- Looking for png_create_read_struct
    -- Looking for png_create_read_struct - found
    -- Looking for jpeg_read_header
    -- Looking for jpeg_read_header - found
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for module 'lapack'
    --   Found lapack, version 3.6.0
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Found LAPACK library
    -- Found BLAS library
    -- Looking for cblas_ddot
    -- Looking for cblas_ddot - found
    -- Looking for sgesv
    -- Looking for sgesv - not found
    -- Looking for sgesv_
    -- Looking for sgesv_ - found
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    -- Found Python with installed numpy package
    -- Numpy include path '/usr/local/lib/python3.5/dist-packages/numpy/core/include'
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-61bjkblz/dlib/build/temp.linux-x86_64-3.5
    Invoking CMake build: 'cmake --build . --config Release -- -j1'
    Scanning dependencies of target dlib
    [  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    [  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
    [  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
    [  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
    [  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
    [ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
    [ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
    [ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
    [ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
    [ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
    [ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
    [ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
    [ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
    [ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
    [ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
    [ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
    [ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
    [ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
    [ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
    [ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
    [ 32%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
    [ 33%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
    [ 34%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
    [ 35%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
    [ 37%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
    [ 38%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
    [ 39%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
    [ 41%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
    [ 42%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
    [ 43%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
    [ 44%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
    [ 46%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
    [ 47%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
    [ 48%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
    [ 50%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
    [ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
    [ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
    [ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dnn/cpu_dlib.cpp.o
    [ 55%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dnn/tensor_tools.cpp.o
    [ 56%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
    [ 57%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/widgets.cpp.o
    [ 58%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/drawable.cpp.o
    [ 60%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.cpp.o
    [ 61%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/style.cpp.o
    [ 62%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/base_widgets.cpp.o
    [ 64%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.cpp.o
    [ 65%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.cpp.o
    [ 66%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
    [ 67%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
    [ 69%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
    [ 70%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
    [ 71%] Linking CXX static library libdlib.a
    [ 71%] Built target dlib
    Scanning dependencies of target dlib_python
    [ 73%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
    [ 74%] Building CXX object CMakeFiles/dlib_python.dir/src/matrix.cpp.o
    [ 75%] Building CXX object CMakeFiles/dlib_python.dir/src/vector.cpp.o
    [ 76%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o
    [ 78%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o
    [ 79%] Building CXX object CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o
    [ 80%] Building CXX object CMakeFiles/dlib_python.dir/src/other.cpp.o
    [ 82%] Building CXX object CMakeFiles/dlib_python.dir/src/basic.cpp.o
    [ 83%] Building CXX object CMakeFiles/dlib_python.dir/src/cca.cpp.o
    [ 84%] Building CXX object CMakeFiles/dlib_python.dir/src/sequence_segmenter.cpp.o
    [ 85%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_struct.cpp.o
    [ 87%] Building CXX object CMakeFiles/dlib_python.dir/src/image.cpp.o
    [ 88%] Building CXX object CMakeFiles/dlib_python.dir/src/rectangles.cpp.o
    [ 89%] Building CXX object CMakeFiles/dlib_python.dir/src/object_detection.cpp.o
    [ 91%] Building CXX object CMakeFiles/dlib_python.dir/src/shape_predictor.cpp.o
    [ 92%] Building CXX object CMakeFiles/dlib_python.dir/src/correlation_tracker.cpp.o
    [ 93%] Building CXX object CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    CMakeFiles/dlib_python.dir/build.make:446: recipe for target 'CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o' failed
    make[2]: *** [CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o] Error 4
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
    make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-61bjkblz/dlib/setup.py", line 238, in <module>
        'Topic :: Software Development',
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-61bjkblz/dlib/setup.py", line 119, in run
        self.build_extension(ext)
      File "/tmp/pip-build-61bjkblz/dlib/setup.py", line 155, in build_extension
        subprocess.check_call(cmake_build, cwd=build_folder)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-61bjkblz/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-q0ealcj_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-61bjkblz/dlib/
`



Still can't install  requirements.txt without errors
```

**Comment by ThoughtfulDev** [comment]
It seems that dlib has some dependencies...install those like this. 
```
$ sudo apt-get install build-essential cmake
$ sudo apt-get install libgtk-3-dev
$ sudo apt-get install libboost-all-dev
```

Which Ubuntu version are you using?
I tried it with a xubuntu 16.04 live boot at the current Readme worked. But try those last steps. If those work then I will add them to the Readme

**Comment by 20chix** [comment]
I have 16.04 ubuntu on virtualbox:

I will download a fresh version of ubuntu and try again but still getting errors.

`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zdwj9i04/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-17ngb9fa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-zdwj9i04/dlib/`

``

**Comment by ThoughtfulDev** [comment]
That's weird...
So try installing python 3
```
sudo apt install python3 python3-pip python3-dev 
```

Then
```

$ sudo apt-get install build-essential cmake
$ sudo apt-get install libgtk-3-dev
$ sudo apt-get install libboost-all-dev
```

And then follow the Readme. That's what I did on Ubuntu 16.04
Make sure that you use `pip3`

**Comment by ThoughtfulDev** [comment]
I did the follow on a fresh 16.04 Ubuntu Install:
```
$ sudo apt install python3 python3-pip python3-dev
$ sudo apt install libgtk-3-dev libboost-all-dev build-essential cmake libffi-dev
$ git clone https://github.com/ThoughtfulDev/EagleEye
$ cd EagleEye && pip3 install -r requirements.txt
$ sudo pip3 install --upgrade beautifulsoup4 html5lib spry
```

**Comment by 20chix** [comment]
Installing fresh version of ubuntu, will keep you update.

PS you should defenetly  expand this project, few suggestions:
1) Place this project into a server, where a web application or iOS or Android app can use it as you would in a Linux environment
2) Capture faces from a smart phone camera , send it to the server run the software and return to the user with results
3) Improve the algorithm in order to just pass an image, and return with suggestions of the person deatils

If you want I can help with 1)  2) and 3).

**Comment by ThoughtfulDev** [comment]
1. and 2. Thats actually not that hard but i first want to focus on the program itself.
3. This actually works as of right now. You can pass the --skipfb flag to skip the Facebook Search so you wont need a name e.g
`python3 eagle-eye.py --skipfb`

**Comment by 20chix** [comment]
Fresh version of ubuntu 16.04 LTS, still getting stuck into this bit

```
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dm89bazw
/dlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 
'exec'))" install --record /tmp/pip-6uwrkwyu-record/install-record.txt --single-version-externally-managed
 --compile" failed with error code 1 in /tmp/pip-build-dm89bazw/dlib/
``
```

**Comment by 20chix** [comment]
Will try to run this command`pip3 install -r requirements.txt` with `sudo`

**Comment by 20chix** [comment]
```
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_sxch134/dlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-z5_521d0-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-_sxch134/dlib/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' comma
```


Still getting the same error, dont know what else to try

**Comment by 20chix** [comment]
Trying Automated Prequisites Installation from your readme

**Comment by 20chix** [comment]
Still getting same errors with automated

**Comment by ThoughtfulDev** [comment]
I have no Idea why i works on my Iso and not on yours ...
try those last steps:
```
$ sudo apt-get update
$ sudo apt-get install build-essential cmake
$ sudo apt-get install libopenblas-dev liblapack-dev 
$ sudo apt-get install libx11-dev libgtk-3-dev
$ sudo apt-get install python python-dev python-pip
$ sudo apt-get install python3 python3-dev python3-pip
```

then run the automated install script.

**Comment by martmists** [comment]
@20chix please post the full error; we can't do anything with the python command, we need the C logs
